Repository FlorianDefer/securite_cesi, pull requests merged in 2021-06, with the labels that each got.

#9 Add tutorial resources for unit testing and unit testing of the Middleware ErrorHandler
  package-lock.json
  package.json
  test/middleware/errorHandler.js
  test/tutorials.txt
Labels: documentation, enhancement, good first issue

#10 AIG-UnitTesting
  _helpers/db.js
  accounts/account.model.js
  accounts/account.service.js
  package-lock.json
  package.json
  test/api/category/post.js
  test/api/category/post.test.js
  test/middleware/errorHandler.test.js
  test/services/account.js
  test/services/account.service.test.js
Labels: documentation, enhancement

#12 AIG-CategoryPutTest: Add Integration Test for the category PUT API
  test/api/category/put.test.js
Labels: documentation, enhancement

#13 AIG-AccountServiceTesting & Bug fix for authentication
  accounts/account.service.js
  test/services/account.service.test.js
Labels: bug, documentation, enhancement

#15 Revert Email test
  backoffice/connexion.html
Labels: enhancement
